#!/bin/bash
#
# MIT License
#
# (C) Copyright 2021-2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

SCRIPT_DIR=$(dirname $(which $0))

#
# Find newest build_common.shrc
#

# backup old one
if [ -f build_common.shrc ] ; then
  mv build_common.shrc build_common.shrc.bk
fi

# for Jenkins builds - find the directory
COMMON_SUBDIR=multibranch-build-common/branches/master/builds/lastSuccessfulBuild/archive/build
for d in \
  ../../jobs/$COMMON_SUBDIR \
  ../../../jobs/$COMMON_SUBDIR \
  ../../$COMMON_SUBDIR
  do
  if [ -f $SCRIPT_DIR/$d/build_common.shrc ] ; then
    cp --preserve=timestamps $SCRIPT_DIR/$d/build_common.shrc .
    break
  fi
done

source build_common.shrc